#if !canImport(ObjectiveC)
import XCTest

extension SearchResultTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SearchResultTests = [
        ("testArtworkURLForSize", testArtworkURLForSize),
        ("testDecodingFromData", testDecodingFromData),
    ]
}

extension SearchResultTransportPublisherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SearchResultTransportPublisherTests = [
        ("testPerformingRequest", testPerformingRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SearchResultTests.__allTests__SearchResultTests),
        testCase(SearchResultTransportPublisherTests.__allTests__SearchResultTransportPublisherTests),
    ]
}
#endif
